### ISSUE TITLE
Support non-compact mode

### ISSUE THREAD

**Issue by Miserlou** [die-net/dhtproxy#1]
This would be much easier for manually debugging, any reason why compact mode is a requirement?

**Comment by aaron42net** [comment]
Non-compact mode by default returns peer_id, which I have no way to find via DHT.  The no_peer_id extension removes that requirement, but clients that support no_peer_id also generally support compact mode.

It wouldn't be hard to bencode the list of peers instead.  Do you have a client that supports no_peer_id?

**Comment by Miserlou** [comment]
Ahhhhh, I see, that makes total sense. Okay, I think you're right. I'll just use a library to debug rather than the browser.

Thanks for this awesome project! Simple but brilliant.

**Comment by aaron42net** [comment]
No worries, thanks.

I've updated the README with a comment about why it isn't supported.
